# Generated by Django 3.1.2 on 2021-02-04 20:51

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=40, null=True)),
                ('content', models.CharField(max_length=2000, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articleid', models.IntegerField(default=0, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('content', models.CharField(max_length=600, null=True)),
                ('publicationdate', models.DateTimeField()),
                ('dadid', models.IntegerField(default=0, null=True)),
                ('dadname', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dailyrecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisherid', models.IntegerField(default=0)),
                ('theme', models.CharField(max_length=60, null=True)),
                ('contents', models.TextField(max_length=4967295, null=True)),
                ('viewsnumber', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('likesnumber', models.IntegerField(default=0)),
                ('publicationdate', models.DateTimeField()),
                ('image', models.CharField(default='images/moren.jpg', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=100, null=True)),
                ('contents', models.CharField(max_length=800, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('successdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dailyid', models.CharField(max_length=7, null=True)),
                ('labelsname', models.CharField(max_length=20, null=True)),
                ('labelsnumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('webname', models.CharField(max_length=20, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='images')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisherid', models.CharField(max_length=7, null=True)),
                ('photos', models.ImageField(upload_to='pictures')),
                ('uploaddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Say',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisherid', models.CharField(max_length=7, null=True)),
                ('contents', models.CharField(max_length=600, null=True)),
                ('viewsnumber', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('likesnumber', models.IntegerField(default=0)),
                ('publicationdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('headimage', models.ImageField(upload_to='headimages')),
                ('birthday', models.DateField(null=True)),
                ('signs', models.CharField(max_length=60, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
