# Generated by Django 3.1.2 on 2021-02-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0002_auto_20210204_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='wechat',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='weibo',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
