# Generated by Django 3.1.2 on 2021-02-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0003_auto_20210204_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='QQ',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
