# Generated by Django 3.1.2 on 2021-02-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0004_myuser_qq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '网站说明', 'verbose_name_plural': '网站说明'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '评论管理', 'verbose_name_plural': '评论管理'},
        ),
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'verbose_name': '日志管理', 'verbose_name_plural': '日志管理'},
        ),
        migrations.AlterModelOptions(
            name='goals',
            options={'verbose_name': '目标管理', 'verbose_name_plural': '目标管理'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': '友链管理', 'verbose_name_plural': '友链管理'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterModelOptions(
            name='say',
            options={'verbose_name': '说说管理', 'verbose_name_plural': '说说管理'},
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(max_length=4000, null=True, verbose_name='关于内容'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subject',
            field=models.CharField(max_length=40, null=True, verbose_name='关于主题'),
        ),
        migrations.AlterField(
            model_name='about',
            name='time',
            field=models.DateTimeField(verbose_name='关于时间'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='articleid',
            field=models.IntegerField(default=0, null=True, verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(max_length=600, null=True, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='dadid',
            field=models.IntegerField(default=0, null=True, verbose_name='评论父ID'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='dadname',
            field=models.CharField(max_length=20, null=True, verbose_name='评论父姓名'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.CharField(max_length=30, null=True, verbose_name='评论人邮箱'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publicationdate',
            field=models.DateTimeField(verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(max_length=20, null=True, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='contents',
            field=models.TextField(max_length=4967295, null=True, verbose_name='日志内容'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='日志封面图'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='likesnumber',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='publicationdate',
            field=models.DateTimeField(verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='publisherid',
            field=models.IntegerField(default=0, verbose_name='作者ID'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='theme',
            field=models.CharField(max_length=60, null=True, verbose_name='日志主题'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='viewsnumber',
            field=models.IntegerField(default=0, verbose_name='浏览数'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='contents',
            field=models.CharField(max_length=800, null=True, verbose_name='目标内容'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='state',
            field=models.CharField(max_length=50, null=True, verbose_name='目标状态'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='successdate',
            field=models.DateField(verbose_name='未来之期'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='theme',
            field=models.CharField(max_length=100, null=True, verbose_name='目标主题'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='dailyid',
            field=models.CharField(max_length=7, null=True, verbose_name='日志ID'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='labelsname',
            field=models.CharField(max_length=20, null=True, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='labelsnumber',
            field=models.IntegerField(default=0, verbose_name='标签数目'),
        ),
        migrations.AlterField(
            model_name='links',
            name='webname',
            field=models.CharField(max_length=20, null=True, verbose_name='网站名称'),
        ),
        migrations.AlterField(
            model_name='links',
            name='website',
            field=models.CharField(max_length=100, null=True, verbose_name='网站地址'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='QQ',
            field=models.CharField(max_length=11, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='headimage',
            field=models.ImageField(upload_to='headimages', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='signs',
            field=models.CharField(max_length=60, null=True, verbose_name='个签'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='wechat',
            field=models.CharField(max_length=18, null=True, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='weibo',
            field=models.CharField(max_length=18, null=True, verbose_name='微博'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='time',
            field=models.DateTimeField(verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='photos',
            field=models.ImageField(upload_to='pictures', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='publisherid',
            field=models.CharField(max_length=7, null=True, verbose_name='发布者ID'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='uploaddate',
            field=models.DateField(verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='say',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='say',
            name='contents',
            field=models.CharField(max_length=600, null=True, verbose_name='说说内容'),
        ),
        migrations.AlterField(
            model_name='say',
            name='likesnumber',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='say',
            name='publicationdate',
            field=models.DateTimeField(verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='say',
            name='publisherid',
            field=models.CharField(max_length=7, null=True, verbose_name='作者ID'),
        ),
        migrations.AlterField(
            model_name='say',
            name='viewsnumber',
            field=models.IntegerField(default=0, verbose_name='浏览数'),
        ),
    ]
