# Generated by Django 3.1.2 on 2021-02-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0005_auto_20210204_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='名称')),
                ('address', models.FileField(upload_to='files', verbose_name='附件地址')),
                ('time', models.DateTimeField(verbose_name='上传时间')),
            ],
        ),
    ]
